package neg5.api.impl;

import com.google.inject.Inject;
import com.google.inject.persist.Transactional;
import neg5.api.DomainObjectApiLayer;
import org.neg5.FieldValidationErrors;
import org.neg5.core.CurrentUserContext;
import org.neg5.core.UserData;
import org.neg5.daos.AbstractDAO;

import org.neg5.data.AbstractDataObject;
import org.neg5.data.Auditable;
import org.neg5.data.CompositeIdObject;
import org.neg5.data.IdDataObject;
import org.neg5.mappers.AbstractObjectMapper;
import org.neg5.validation.ObjectValidationException;

import javax.persistence.NoResultException;
import java.io.Serializable;
import java.time.Instant;
import java.util.List;
import java.util.Optional;
import java.util.Set;
import java.util.stream.Collectors;

public abstract class AbstractApiLayerImpl<T extends AbstractDataObject<T>
        & IdDataObject<IdType>, DTO, IdType extends Serializable> implements DomainObjectApiLayer<DTO, IdType> {

    @Inject private CurrentUserContext userContext;

    protected abstract AbstractDAO<T, IdType> getDao();

    protected abstract AbstractObjectMapper<T, DTO> getMapper();

    @Transactional
    @Override
    public DTO get(IdType id) {
        T entity = getDao().get(id);
        if (entity == null) {
            String clazzName = getDao().getPersistentClass().getSimpleName();
            throw new NoResultException("No result found for " + clazzName + " with id " + id);
        }
        return getMapper().toDTO(entity.copyOf());
    }

    public List<DTO> get(Set<IdType> ids) {
        return ids.stream().map(id -> get(id)).collect(Collectors.toList());
    }

    @Transactional
    @Override
    public DTO create(DTO dto) {
        validateInternal(dto);
        T entity = getMapper().mergeToEntity(dto);

        /* Assumption is that if the entity doesn't have a composite primary key,
        the id will be auto-generated by Hibernate.
        */
        if (!(entity instanceof CompositeIdObject)) {
            entity.setId(null);
        }
        if (entity instanceof Auditable) {
            UserData userData = userContext.getUserData().get();
            ((Auditable) entity).setAddedBy(userData.getUsername());
            ((Auditable) entity).setAddedAt(Instant.now());
        }
        T createdEntity = getDao().save(entity);
        getDao().flush();
        return getMapper().toDTO(getDao().get(createdEntity.getId()));
    }

    @Transactional
    @Override
    public DTO update(DTO dto) {
        validateInternal(dto);
        updateInternal(dto);
        return get(getIdFromDTO(dto));
    }

    @Transactional
    @Override
    public void delete(IdType id) {
        getDao().delete(id);
    }

    @Transactional
    @Override
    public void delete(DTO collaborator) {
        delete(getIdFromDTO(collaborator));
    }

    @Transactional
    @Override
    public List<DTO> findAllByTournamentId(String tournamentId) {
        return getDao().findAllByTournamentId(tournamentId)
                .stream()
                .map(entity -> getMapper().toDTO(entity))
                .collect(Collectors.toList());
    }

    protected Optional<FieldValidationErrors> validateObject(DTO dto) {
        return Optional.empty();
    }

    protected void updateInternal(DTO dto) {
        T originalEntity = getDao().get(getIdFromDTO(dto));
        T updated = getMapper().mergeToEntity(dto, originalEntity);
        getMapper().toDTO(getDao().save(updated).copyOf());
    }

    protected IdType getIdFromDTO(DTO dto) {
        return getMapper().mergeToEntity(dto).getId();
    }

    private void validateInternal(DTO dto) {
        Optional<FieldValidationErrors> errors = validateObject(dto);
        errors.filter(error -> !error.getErrors().isEmpty()).ifPresent(error -> {
            throw new ObjectValidationException(error);
        });
    }
}
