# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Java CI with Maven

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    env:
      PORT: 1337
      NEG5_ENVIRONMENT: CI
      NEG5_JWT: ${{ secrets.NEG5JWT }}
    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Build and Unit Test
      run: mvn -B package --file pom.xml
    - name: Spotless Check
      run: mvn spotless:check
    - name: Create Postgres Database
      run: ./db/bin/bootstrap_local_db.sh
    - name: Start Service
      run: |
        cd app
        java -Xmx256m -javaagent:./target/newrelic/newrelic.jar -jar ./target/app-1.0-SNAPSHOT-jar-with-dependencies.jar & sleep 20
    - name: Verify Service is Running
      run: curl http://localhost:$PORT
    - name: Run API Tests
      run: mvn failsafe:integration-test failsafe:verify
      continue-on-error: true