# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Java CI with Maven

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build-and-deploy:

    runs-on: ubuntu-latest
    env:
      PORT: 1337
      NEG5_ENVIRONMENT: CI
      NEG5_JWT: ${{ secrets.NEG5JWT }}
    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Build with Maven
      run: mvn -B package --file pom.xml
    - name: Spotless Check
      run: mvn spotless:check
    - name: Create Database
      run: ./neg5.db/bin/bootstrap_local_db.sh
    - name: Start Service
      run: |
        java -Xmx128m -jar ./service/target/neg5.service-1.0-SNAPSHOT-jar-with-dependencies.jar & sleep 20
    - name: Service Health Check
      run: curl http://localhost:$PORT
